# Generated by Django 4.2.4 on 2023-08-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kurier_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='user',
        ),
    ]
